# generated by datamodel-codegen:
#   filename:  openspec.yml
#   timestamp: 2024-07-30T17:00:26+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class V1CubeMetaJoin(BaseModel):
    name: str
    relationship: str


class V1CubeMetaSegment(BaseModel):
    name: str
    title: str
    shortTitle: str


class V1CubeMetaDimension(BaseModel):
    name: str
    type: str


class V1CubeMetaMeasure(BaseModel):
    name: str
    title: Optional[str] = None
    type: str
    aggType: Optional[str] = None


class V1CubeMeta(BaseModel):
    name: str
    title: Optional[str] = None
    measures: List[V1CubeMetaMeasure]
    dimensions: List[V1CubeMetaDimension]
    segments: List[V1CubeMetaSegment]
    joins: Optional[List[V1CubeMetaJoin]] = None


class V1MetaResponse(BaseModel):
    cubes: Optional[List[V1CubeMeta]] = None
